function [PlotVar1DMaps, PlotVarDecoder, PlotVarPop, PlotVarBehavior] = DefinePlotVariable
PlotVar1DMaps = Tstructure('PlotVar1DMaps');
PlotVar1DMaps.addprop('Shanknum');
PlotVar1DMaps.Shanknum = [0:7 0];
PlotVar1DMaps.addprop('Shanksuffix');
PlotVar1DMaps.Shanksuffix = {'CA1','CA1','CA1','CA1','CA1','CA1','CA1','CA1','V1'};
PlotVar1DMaps.addprop('FXcond');
PlotVar1DMaps.FXcond = true;
PlotVar1DMaps.addprop('ChosenCell');
PlotVar1DMaps.ChosenCell = 1;
PlotVar1DMaps.addprop('FpoolCell');
PlotVar1DMaps.FpoolCell = 0;
PlotVar1DMaps.addprop('speed_th');
PlotVar1DMaps.speed_th = 5;
PlotVar1DMaps.addprop('ChosenContrast');
PlotVar1DMaps.ChosenContrast = 1;
PlotVar1DMaps.addprop('FpoolContrast');
PlotVar1DMaps.FpoolContrast = 0;
PlotVar1DMaps.addprop('ChosenGain');
PlotVar1DMaps.ChosenGain = 1;
PlotVar1DMaps.addprop('FpoolGain');
PlotVar1DMaps.FpoolGain = 0;
PlotVar1DMaps.addprop('ChosenRoomlength');
PlotVar1DMaps.ChosenRoomlength = 1;
PlotVar1DMaps.addprop('FpoolRoomlength');
PlotVar1DMaps.FpoolRoomlength = 0;
PlotVar1DMaps.addprop('ChosenOutcome');
PlotVar1DMaps.ChosenOutcome = 1;
PlotVar1DMaps.addprop('FpoolOutcome');
PlotVar1DMaps.FpoolOutcome = 0;
PlotVar1DMaps.addprop('ChosenVarY');
PlotVar1DMaps.ChosenVarY = 'traj';
PlotVar1DMaps.addprop('ChosenVarX');
PlotVar1DMaps.ChosenVarX = 'trial';
PlotVar1DMaps.addprop('ChosenObj');
PlotVar1DMaps.ChosenObj = 'Raster';
PlotVar1DMaps.addprop('samplerate');
PlotVar1DMaps.samplerate = 60;
PlotVar1DMaps.addprop('Nthetaphsbins');
PlotVar1DMaps.Nthetaphsbins = 0;
PlotVar1DMaps.addprop('SpeedThreshold');
PlotVar1DMaps.SpeedThreshold = 5;
PlotVar1DMaps.addprop('SmthTimeWindow');
PlotVar1DMaps.SmthTimeWindow = 15;
PlotVar1DMaps.addprop('SmthSpatialWindow');
PlotVar1DMaps.SmthSpatialWindow = 2;
PlotVar1DMaps.addprop('FloadfromfileCellinfo');
PlotVar1DMaps.FloadfromfileCellinfo = 0;
PlotVar1DMaps.addprop('delayT');
PlotVar1DMaps.delayT = 0;
PlotVar1DMaps.addprop('Xbinsize');
PlotVar1DMaps.Xbinsize = 2.5;
PlotVar1DMaps.addprop('thetaChannel');
PlotVar1DMaps.thetaChannel = 34;
PlotVar1DMaps.addprop('explist');
PlotVar1DMaps.explist = 101;
PlotVar1DMaps.addprop('Plots');
PlotVar1DMaps.Plots = [];
PlotVar1DMaps.addprop('Fdispmat');
PlotVar1DMaps.Fdispmat = false;
PlotVar1DMaps.addprop('PlotVarList');
PlotVar1DMaps.PlotVarList = {'trajPercent', 'traj', 'trialID', 'smthBallSpd', 'ballspeed', 'trajspeed', 'smthBallAcc', 'smthTrajSpd', 'totDistTrav', 'distTrav', 'currTime', 'runTime'};
PlotVar1DMaps.addprop('PlotObjList');
PlotVar1DMaps.PlotObjList = {'Raster', 'fast1Dmap', '1Dmap', '2DmapXSpd', '2DmapXTheta', 'Theta', 'POTH', 'Xpos', 'Ypos', 'Ori', 'Xpos x Ypos'};

PlotVarDecoder = Tstructure('PlotVarDecoder');
PlotVarDecoder.addprop('TrainContrast');
PlotVarDecoder.TrainContrast = 0.5;
PlotVarDecoder.addprop('TrainGain');
PlotVarDecoder.TrainGain = 1;
PlotVarDecoder.addprop('TrainRoomLength');
PlotVarDecoder.TrainRoomLength = 1;
PlotVarDecoder.addprop('TrainOutcome');
PlotVarDecoder.TrainOutcome = 2;
PlotVarDecoder.addprop('ChosenProbe');
PlotVarDecoder.ChosenProbe = 1;
PlotVarDecoder.addprop('PlotObjList');
PlotVarDecoder.PlotObjList = {'Posterior x X', 'Posterior x D','Posterior x Time', 'Projection 45', 'Error x X', 'Error x D', 'Error x Time', 'Mean X-Error', 'Mean D-Error', 'Theta x Error x X', 'Theta x Post x X', 'Theta x Error phase'};
PlotVarDecoder.addprop('ChosenContrast');
PlotVarDecoder.ChosenContrast = 1;
PlotVarDecoder.addprop('FpoolContrast');
PlotVarDecoder.FpoolContrast = 0;
PlotVarDecoder.addprop('ChosenGain');
PlotVarDecoder.ChosenGain = 1;
PlotVarDecoder.addprop('FpoolGain');
PlotVarDecoder.FpoolGain = 0;
PlotVarDecoder.addprop('ChosenRoomlength');
PlotVarDecoder.ChosenRoomlength = 1;
PlotVarDecoder.addprop('FpoolRoomlength');
PlotVarDecoder.FpoolRoomlength = 0;
PlotVarDecoder.addprop('ChosenOutcome');
PlotVarDecoder.ChosenOutcome = 1;
PlotVarDecoder.addprop('FpoolOutcome');
PlotVarDecoder.FpoolOutcome = 0;
PlotVarDecoder.addprop('ChosenObj');
PlotVarDecoder.ChosenObj = 'Posterior x X';
PlotVarDecoder.addprop('Fdisplaylog');
PlotVarDecoder.Fdisplaylog = 0;
PlotVarDecoder.addprop('Clim');
PlotVarDecoder.Clim = [0.5 1.5];
PlotVarDecoder.addprop('Fnormalize');
PlotVarDecoder.Fnormalize = 0;
PlotVarDecoder.addprop('explist');
PlotVarDecoder.explist = 101;
PlotVarDecoder.addprop('FdecXdistribution');
PlotVarDecoder.FdecXdistribution = false;
PlotVarDecoder.addprop('maxtolerance');
PlotVarDecoder.maxtolerance = 0.1;
PlotVarDecoder.addprop('Fgoodtimebins');
PlotVarDecoder.Fgoodtimebins = false;
PlotVarDecoder.addprop('Fspatialsmooth');
PlotVarDecoder.Fspatialsmooth = true;
PlotVarDecoder.addprop('FthetaPost');
PlotVarDecoder.FthetaPost = false;
PlotVarDecoder.addprop('thetaDecphase');
PlotVarDecoder.thetaDecphase = 0; 
PlotVarDecoder.addprop('Fthetabins');
PlotVarDecoder.Fthetabins = false;
PlotVarDecoder.addprop('thetaChannel');
PlotVarDecoder.thetaChannel = 34;
PlotVarDecoder.addprop('thetaphase');
PlotVarDecoder.thetaphase = 0;
PlotVarDecoder.addprop('nthetaphsbins');
PlotVarDecoder.nthetaphsbins = 12;
PlotVarDecoder.addprop('nthetaXbins');
PlotVarDecoder.nthetaXbins = 50;
PlotVarDecoder.addprop('Fspdbins');
PlotVarDecoder.Fspdbins = false;
PlotVarDecoder.addprop('spdbin');
PlotVarDecoder.spdbin = 1;
PlotVarDecoder.addprop('Palettename');
PlotVarDecoder.Palettename = 'RedWhiteBlue';
PlotVarDecoder.addprop('Foverlap');
PlotVarDecoder.Foverlap = false;
PlotVarDecoder.addprop('FdisplayLFP');
PlotVarDecoder.FdisplayLFP = true;
PlotVarDecoder.addprop('FdisplayMat');
PlotVarDecoder.FdisplayMat = true;
PlotVarDecoder.addprop('FdisplayPredMax');
PlotVarDecoder.FdisplayPredMax = false;
PlotVarDecoder.addprop('FdisplayPredAve');
PlotVarDecoder.FdisplayPredAve = true;
PlotVarDecoder.addprop('Plots');
PlotVarDecoder.Plots = [];

PlotVarPop = Tstructure('PlotVarPop');
PlotVarPop.addprop('explist');
PlotVarPop.explist = 101;
PlotVarPop.addprop('ChosenContrast');
PlotVarPop.ChosenContrast = 1;
PlotVarPop.addprop('FpoolContrast');
PlotVarPop.FpoolContrast = 0;
PlotVarPop.addprop('ChosenGain');
PlotVarPop.ChosenGain = 1;
PlotVarPop.addprop('FpoolGain');
PlotVarPop.FpoolGain = 0;
PlotVarPop.addprop('ChosenRoomlength');
PlotVarPop.ChosenRoomlength = 1;
PlotVarPop.addprop('FpoolRoomlength');
PlotVarPop.FpoolRoomlength = 0;
PlotVarPop.addprop('ChosenOutcome');
PlotVarPop.ChosenOutcome = 1;
PlotVarPop.addprop('FpoolOutcome');
PlotVarPop.FpoolOutcome = 0;
PlotVarPop.addprop('ChosenObj');
PlotVarPop.ChosenObj = 'fields';
PlotVarPop.addprop('SSIrange');
PlotVarPop.SSIrange = [0 +inf];
PlotVarPop.addprop('Raterange');
PlotVarPop.Raterange = [0 +inf];
PlotVarPop.addprop('Probes');
PlotVarPop.Probes = 1;
PlotVarPop.addprop('zth');
PlotVarPop.zth = -inf;
PlotVarPop.addprop('Plots');
PlotVarPop.Plots = [];
PlotVarPop.addprop('FNormalize');
PlotVarPop.FNormalize = true;
PlotVarPop.addprop('Clim');
PlotVarPop.Clim = [0 1];
PlotVarPop.addprop('PlotObjList');
PlotVarPop.PlotObjList = {'fields', 'theta precession', 'distri fieldpos', 'distri X shift', 'distri SSI', 'distri max rate', 'distri theta coupling'};



PlotVarBehavior = Tstructure('PlotVarBehavior');
PlotVarBehavior.addprop('explist');
PlotVarBehavior.explist = 101;
PlotVarBehavior.addprop('PlotObjList');
PlotVarBehavior.PlotObjList = {'Traj x Time','Speed x Time', 'run Speed x X', 'visual Speed x X', 'eye Xpos', 'eye Ypos', 'pupil Size', 'Licks x X','Cum. Licks x X'};
PlotVarBehavior.addprop('speed_th');
PlotVarBehavior.speed_th = 5;
PlotVarBehavior.addprop('ChosenContrast');
PlotVarBehavior.ChosenContrast = 1;
PlotVarBehavior.addprop('FpoolContrast');
PlotVarBehavior.FpoolContrast = 0;
PlotVarBehavior.addprop('ChosenGain');
PlotVarBehavior.ChosenGain = 1;
PlotVarBehavior.addprop('FpoolGain');
PlotVarBehavior.FpoolGain = 0;
PlotVarBehavior.addprop('ChosenRoomlength');
PlotVarBehavior.ChosenRoomlength = 1;
PlotVarBehavior.addprop('FpoolRoomlength');
PlotVarBehavior.FpoolRoomlength = 0;
PlotVarBehavior.addprop('ChosenOutcome');
PlotVarBehavior.ChosenOutcome = 1;
PlotVarBehavior.addprop('FpoolOutcome');
PlotVarBehavior.FpoolOutcome = 0;
PlotVarBehavior.addprop('ChosenObj');
PlotVarBehavior.ChosenObj = 'Posterior x X';
PlotVarBehavior.addprop('Plots');
PlotVarBehavior.Plots = [];

end